`timescale 1ns / 1ps
///////////////////////////////////////////////////////////////////
// Filename: fv_axil_props.sv
// Purpose : AXI4-Lite slave protocol compliance for the mixer's control port,
//           plus the interrupt.
//
//           The register block is generated by corsair and the adapter around
//           it by regs/gen_regs.py, so nobody reviews this RTL line by line --
//           which is exactly why it is worth checking mechanically. A
//           generated block that violates the protocol is not a hypothetical:
//           a response channel that drops BVALID before BREADY, or that
//           changes RDATA under a master that has not accepted it, hangs or
//           corrupts a processor bus, and the symptom is a wedged CPU rather
//           than a wrong picture.
//
//           Checked here:
//
//             Handshake stability   VALID, once asserted, stays asserted until
//                                   the matching READY, and the payload it
//                                   carries does not change underneath it.
//                                   This is the AXI rule that cannot be
//                                   recovered from -- everything else is a
//                                   performance question.
//
//             Response codes        OKAY on every access. The map decodes the
//                                   whole address space it claims, so there is
//                                   nothing for it to answer SLVERR to, and a
//                                   DECERR appearing anyway would be a decode
//                                   bug.
//
//             Interrupt             irq is exactly the OR of ERR & IRQ_EN, and
//                                   is level sensitive: it stays up until
//                                   software clears the underlying ERR bit.
//                                   A pulse instead of a level loses
//                                   interrupts on a shared line.
//
//           Everything in this file closes under k-induction, which is why the
//           two AXI4-Lite properties that do NOT are somewhere else:
//
//             No unsolicited response -- a write response only after a write,
//             a read response only after a read address -- needs a count of
//             what is outstanding, and an arbitrary induction start state can
//             put that count at zero with a response already offered.
//
//             Bounded response latency needs a wait counter, with the same
//             problem.
//
//           Both live in tops/fv_top.sv as bounded results, alongside the
//           transaction counters they are built on. Keeping them out of here
//           means this file's result is unconditional, and it means the
//           bookkeeping sits with the environment modelling rather than
//           pretending to be a property of the slave.
///////////////////////////////////////////////////////////////////

module fv_axil_props #(
    parameter int P_ADDR_W = 12,
    parameter int P_NUM_ERR = 5
) (
    input logic clk,
    input logic rst_n,

    input logic [P_ADDR_W-1:0] awaddr,
    input logic                awvalid,
    input logic                awready,
    input logic [        31:0] wdata,
    input logic [         3:0] wstrb,
    input logic                wvalid,
    input logic                wready,
    input logic [         1:0] bresp,
    input logic                bvalid,
    input logic                bready,
    input logic [P_ADDR_W-1:0] araddr,
    input logic                arvalid,
    input logic                arready,
    input logic [        31:0] rdata,
    input logic [         1:0] rresp,
    input logic                rvalid,
    input logic                rready,

    input logic                 irq,
    input logic [P_NUM_ERR-1:0] err_ff,
    input logic [P_NUM_ERR-1:0] irq_en,
    input logic [P_NUM_ERR-1:0] err_set,
    input logic                 err_wr_clear
);
  localparam logic [1:0] RESP_OKAY = 2'b00;

  logic fv_started = 1'b0;
  always_ff @(posedge clk) fv_started <= 1'b1;

  logic bvalid_d, rvalid_d, rst_n_d;
  logic [ 1:0] bresp_d, rresp_d;
  logic [31:0] rdata_d;
  logic bstall_d, rstall_d;

  always_ff @(posedge clk) begin
    rst_n_d  <= rst_n;
    bvalid_d <= bvalid;
    rvalid_d <= rvalid;
    bresp_d  <= bresp;
    rresp_d  <= rresp;
    rdata_d  <= rdata;
    bstall_d <= bvalid && !bready;
    rstall_d <= rvalid && !rready;
  end

  logic ran;
  assign ran = fv_started && rst_n && rst_n_d;

  ////////////////////////////////////////////////////////////////////////////////////////////////////
  // Response channel stability
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  always_ff @(posedge clk) begin
    if (ran && bstall_d) begin
      // A write response offered and not yet accepted must still be there, and
      // must still say the same thing. Withdrawing it leaves the master
      // waiting for a response that has already been and gone.
      a_bvalid_held : assert (bvalid);
      a_bresp_held : assert (bresp == bresp_d);
    end

    if (ran && rstall_d) begin
      // Same for reads, and here the payload matters as well as the handshake:
      // RDATA changing under a master that has not accepted it yet returns the
      // wrong register's contents.
      a_rvalid_held : assert (rvalid);
      a_rdata_held : assert (rdata == rdata_d);
      a_rresp_held : assert (rresp == rresp_d);
    end
  end

  ////////////////////////////////////////////////////////////////////////////////////////////////////
  // Response codes
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  always_ff @(posedge clk) begin
    if (rst_n) begin
      // The map decodes the whole space it claims, so every access is OKAY.
      // A SLVERR or DECERR appearing here would mean an address the map
      // advertises is not actually decoded.
      if (bvalid) a_bresp_okay : assert (bresp == RESP_OKAY);
      if (rvalid) a_rresp_okay : assert (rresp == RESP_OKAY);
    end
  end

  ////////////////////////////////////////////////////////////////////////////////////////////////////
  // Interrupt
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  always_ff @(posedge clk) begin
    if (rst_n) begin
      // Level sensitive and exactly the masked OR, so it stays asserted until
      // software clears the ERR bit behind it. A pulse would be lost on a
      // shared interrupt line, and a level that did not clear would wedge the
      // handler.
      a_irq_is_masked_or : assert (irq == (|(err_ff & irq_en)));

    end
  end

  ////////////////////////////////////////////////////////////////////////////////////////////////////
  // ERR is sticky, and a set beats a clear
  //
  // Every fault has to be latched, attributable and clearable (R8), and the
  // hard part of that is the ordering. corsair gives the hardware set priority
  // over the software clear by design, so an error arriving in the same cycle
  // as its acknowledgement is not lost -- and the adapter's mirror has to
  // match, or STATUS.ERR_ANY and irq disagree with what software reads back
  // out of ERR.
  //
  // Per bit, in a generate loop: a labelled assertion inside a procedural for
  // loop would unroll into five checks with the same name, which yosys-slang
  // refuses.
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  logic [P_NUM_ERR-1:0] err_ff_d, err_set_d;
  logic [         31:0] wdata_d;
  logic [          3:0] wstrb_d;
  logic                 err_wr_clear_d;

  always_ff @(posedge clk) begin
    err_ff_d       <= err_ff;
    err_set_d      <= err_set;
    wdata_d        <= wdata;
    wstrb_d        <= wstrb;
    err_wr_clear_d <= err_wr_clear;
  end

  for (genvar gb = 0; gb < P_NUM_ERR; gb++) begin : g_err
    always_ff @(posedge clk) begin
      if (ran) begin
        // A set is never lost, whatever software is doing in the same cycle.
        if (err_set_d[gb]) begin
          a_err_set_wins : assert (err_ff[gb]);
        end

        // And a bit only ever clears because software wrote a one to it. An
        // error that cleared itself would be a fault software never saw.
        if (err_ff_d[gb] && !err_ff[gb]) begin
          a_err_sticky : assert (err_wr_clear_d && wstrb_d[0] && wdata_d[gb]);
        end
      end
    end
  end

  ////////////////////////////////////////////////////////////////////////////////////////////////////
  // Cover
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  always_ff @(posedge clk) begin
    if (rst_n) begin
      c_write_done : cover (bvalid && bready);
      c_read_done : cover (rvalid && rready);
      c_write_backpressured : cover (bvalid && !bready);
      c_read_backpressured : cover (rvalid && !rready);
      c_irq : cover (irq);
      c_irq_masked : cover ((|err_ff) && !irq);
    end
  end

endmodule
